---
title: "HR Attrition"
author: "Greg"
date: "9 August 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r calcs, echo=FALSE, warning=FALSE, message=FALSE}

library(tidyverse)
library(corrgram)
library(ggthemes)
library(party)
library(caret)
library(randomForest)
library(plotly)
library(htmlwidgets)
library(DT)


commute_data_raw <- read.csv("data/commute_data.csv")
hr_performance_data_raw <- read.csv("data/hr_employees_performance_data.csv")
personal_data_raw <- read.csv("data/personal_data.csv", stringsAsFactors = FALSE)
rnd_performance_data_raw <- read.csv("data/research_and_development_employees_performance_data.csv")
sales_performance_data_raw <- read.csv("data/sales_employees_performance_data.csv")




# Data clean-up -----------------------------------------------------------


personal_data <- personal_data_raw %>%
  spread(key = Variable, value = Value) %>%
  mutate(Age = as.integer(Age),
         Attrition = as.factor(Attrition),
         Education = as.integer(Education),
         EducationField = as.factor(EducationField),
         Gender = as.factor(Gender),
         MaritalStatus = as.factor(MaritalStatus),
         RelationshipSatisfaction = as.integer(RelationshipSatisfaction)) %>%
  select(-EmployeeCount)


hr_performance_data <- select(hr_performance_data_raw, -X)
rnd_performance_data <- select(rnd_performance_data_raw, -X)
sales_performance_data <- select(sales_performance_data_raw, -X)
commute_data <- select(commute_data_raw, -X)


hr_performance_data$Department <- "HR"
rnd_performance_data <- mutate(rnd_performance_data, Department = "Research and Development")
sales_performance_data <- sales_performance_data %>%
  mutate(Department = "Sales")

performance_data <- rbind(hr_performance_data, rnd_performance_data, sales_performance_data)

performance_data <- mutate(performance_data, Department = as.factor(Department))

employee_data <- left_join(performance_data, commute_data, by = "EmployeeNumber")
employee_data <- inner_join(employee_data, personal_data, by = "EmployeeNumber")

employee_data <- performance_data %>%
  left_join(commute_data, by = "EmployeeNumber") %>%
  left_join(personal_data, by = "EmployeeNumber")



employee_data <- employee_data %>%
  mutate(EnvironmentSatisfaction = as.factor(EnvironmentSatisfaction),
         JobInvolvement = as.factor(JobInvolvement),
         JobLevel = as.factor(JobLevel),
         JobSatisfaction = as.factor(JobSatisfaction),
         PerformanceRating = as.factor(PerformanceRating),
         StockOptionLevel = as.factor(StockOptionLevel),
         WorkLifeBalance = as.factor(WorkLifeBalance),
         Education = as.factor(Education),
         RelationshipSatisfaction = as.factor(RelationshipSatisfaction))


dataSpliter <- function(employee_data, p = 0.7){
  set.seed(15)
  num_obs <- dim(employee_data)[1]
  draw <- sample(1:num_obs, replace = FALSE)
  draw_split <- floor(num_obs * p)
  train <- employee_data[draw[1:draw_split],]
  test <- employee_data[draw[(draw_split+1):num_obs],]
  result <- list(train=train, test = test)
  return(result)
}

employee_allsets <- dataSpliter(employee_data, p=0.7)
employee_trainset <- employee_allsets$train
employee_testset <- employee_allsets$test


employees_current <- employee_data %>%
  filter(Attrition == "No")

```


# Models

```{r models}
train_ctree <- ctree(data = employee_trainset, formula = Attrition ~ .)
predict_ctree <- predict(train_ctree, employee_testset)
confusionMatrix(predict_ctree, employee_testset$Attrition)
plot(train_ctree)

rand_forest <- randomForest(data = employee_trainset, Attrition ~ ., importance = TRUE )
predict_forest <- predict(rand_forest, employee_testset)
confusionMatrix(predict_forest, employee_testset$Attrition)
importance_rand_forest <- importance(rand_forest)
importance_rand_forest

```

The mean decrease in accuracy for Overtime was: `r importance_rand_forest[rownames(importance_rand_forest) == "OverTime", 3]`.

# Graphs

```{r graphs, echo=FALSE}
p1 <- ggplot(data = employee_data) +
  geom_bar(aes(x = OverTime, fill = Attrition), position = "fill") +
  ggtitle("Percentage Attrition by Overtime") +
  scale_fill_colorblind()

ggplotly(p1)

```


# Tables

```{r tables, echo=FALSE}

current_prediction_ctree <- predict(train_ctree, employees_current)
employees_current$PredictedAttrition <- current_prediction_ctree
likely_to_leave_list1 <- employees_current %>% 
  filter(PredictedAttrition == "Yes")

current_prediction_forest <- predict(rand_forest, employees_current)
employees_current$PredictedAttrition2 <- current_prediction_forest
likely_to_leave_list2 <- employees_current %>%
  filter(PredictedAttrition2 == "Yes")

datatable(likely_to_leave_list1)
datatable(likely_to_leave_list2)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


# Neural Networks and Attrition




